import os 
import subprocess

here = os.path.abspath(os.path.dirname(__file__))

def updateversion(here=here):
    # Fetch version from git tags, and write to version.py
    # Also, when git is not available (PyPi package), use stored version.py
    version_py = os.path.join(here,"version.py")
    version_txt = os.path.join(here,"version.txt")
    try:
        version_git = subprocess.check_output(["git","describe"]).rstrip().decode()
    except:
        with open(version_py,'r') as fh:
            version_git = open(version_py).read().strip().split("=")[-1].replace('""','')

    version_msg = "# Do not edit this file, pipeline versioning is governed by git tags !"
    with open(version_py,"w") as fh:
        fh.write((version_msg + os.linesep + '__version__=').replace('',"") + "'%s'" % version_git)
    with open(version_txt,"w") as fh:
        fh.write(version_git.replace('-','.'))
    return version_git




