[build-system]
requires = [
        "setuptools>=40.8.0, <64",
	"wheel",
	"Cython>=0.26",
	"numpy",
]
build-backend = "setuptools.build_meta"

[project]
name = "tofu"
dynamic = ["version"]
description="A python library for Tomography for Fusion"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
]
authors = [
    { name = "Didier Vezinet", email = "didier.vezinet@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "setuptools>=40.8.0, <64",
    "numpy",
    "scipy",
    # "scikit-sparse",
    # "scikit-umfpack",
    "matplotlib",
    "contourpy",
    "requests",
    "svg.path",
    "Polygon3",
    "cython>=0.26",
    "datastock>=0.0.49",
    "bsplines2d>=0.0.21",
    "spectrally>=0.0.9",
]

[project.optional-dependencies]
interactive = ["PyQt5", "PySide2"]

[tool.setuptools.packages.find]
where = ["tofu"]

[tool.setuptools.package-data]
"*" = ["*.txt", "*.csv", "*.pxd", "*.in", "*.toml", "*.npz", "*.svg", "*.sh", "*.f"]

[tool.coverage.report]
precision = 2
fail_under = 85

[tool.pytest.ini_options]
testpaths = [
  "tofu.tests",
]

[project.urls]
Homepage = "https://tofuproject.github.io/tofu/index.html"
Documentation = "https://tofuproject.github.io/tofu/index.html"
Repository = "https://github.com/ToFuProject/tofu"
"Bug Tracker" = "https://github.com/ToFuProject/tofu/issues"
