<<<<<<< HEAD
=======
# Autogenerated by Tofu's setup.py on 2021-09-21 12:16:52
>>>>>>> 20de072f ([#75] checking bug)
def is_openmp_enabled():
    """
    Determine whether this package was built with OpenMP support.
    """
    return True
