package:
  name: 'tofu'
  version: {{ environ['VERSION'] }}

source:
  git_url: https://github.com/ToFuProject/tofu.git
  git_rev: {{ environ['REV'] }}

build:
  script_env:
    - PKG_REAL
    - TRAVIS_BRANCH

requirements:

  # build: necessary for build.sh
  # here same as run, as we are using cython
  build:
    - python
    - setuptools >=40.8.0
    - setuptools_scm
    - numpy
    - scipy
    - matplotlib
    - Cython >=0.26
    - pytest
    - pygments


  # for running the library
  run:
    - python
    - setuptools
    - setuptools_scm
    - numpy
    - scipy
    - matplotlib
    - Cython >=0.26
    - pytest
    - pygments

test:
  requires:
    - pytest
  imports:
    - tofu.geom

about:
  home: https://github.com/ToFuProject/tofu
  license: MIT
  license_file: LICENSE.txt
  summary: Tomography for Fusion

# conda build -c tofuproject conda_recipe/
